import Navbar from '@/components/NavBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} h-screen overflow-x-hidden overflow-y-scroll flex`}
      >
        <div className='bg-white text-black'>
          <Navbar />
          {/* <div className='pt-28 h-screen'>{children}</div> */}
          <div className=' h-screen'>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
